spawner:
  # Only for this feature, when world uuid is changed, limit will be reset.
  max-minable-spawners:
    default:
      DEFAULT: 2
    world: {}
    resource:
      ZOMBIE: 2

  max-spawnable-mobs:
    default:
      DEFAULT: 100000
    world: {}
    resource:
      ZOMBIE: 100000

  # Limits spanwer amount in specific radius (circle)
  # Only player placement will be affected.
  isolating:
    enabled: true
    radius: 34
    amount: 2
  
  redstone-switches-spawner:
    default:
      # If enabled false, redstone power will not affect spawners.
      # reversed value are ignored at the situation. 
      enabled: false
      # If reversed is false, spawners will stop when redstone powered.
      # If true, spawners will start when redstone powered.
      reversed: false
    world:
      enabled: false
      reversed: false
    tt:
      enabled: true
      reversed: true


# Stack mobs.
mob-stacker:
  enabled: true
  target-spawn-reason:
    - SPAWNER

# Find mob farms.
# If spawn reason includes BLEEDING,
# you can also find normal farm which is not grinder.
find-farms:
  enabled: true
  killing-chumber-range: 2
  # Amount of killed mobs to consider the location as killing-chumber in the range specified above.
  killed-mobs-to-be-killing-chumber: 30
  farm-actions:
    SPAWNER: []
    NATURAL:
      - CLEAR_DROP
      - CLEAR_EXP
      - NOTIFY
    NETHER_PORTAL:
      - CLEAR_DROP
      - CLEAR_EXP
      - NOTIFY
    PATROL:
      - CLEAR_DROP
      - CLEAR_EXP
      - NOTIFY
    VILLAGE_DEFENSE:
      - CLEAR_DROP
      - CLEAR_EXP
      - NOTIFY
    VILLAGE_INVASION:
      - CLEAR_DROP
      - CLEAR_EXP
      - NOTIFY
    RAID:
      - CLEAR_DROP
      - CLEAR_EXP
      - NOTIFY
    SLIME_SPLIT:
      - CLEAR_DROP
      - CLEAR_EXP
      - NOTIFY

anti-clickbot:
  enabled: true
  # Available types are: SUMMON_ENEMY, CANCEL, KILL, KICK, CALL_ADMIN
  # SUMMON_ENEMY will teleport nearest agressive mobs
  # CANCEL will cancel clicks
  # KILL will kill clicking player
  # KICK will kick clicking player
  # CALL_ADMIN will notify admins that click bot is used.
  type: SUMMON_ENEMY
  warn-before: true
  warn-message: "You are using auto clicking tools. If you continue to use this, something bad will happen to you!"

prevent-cramming-death-drop: true