spawner:
  unbreakable:
    # breaking "mob-type" spawner by players will be cancelled.
    mob-types:
      # - ALL
      - CREEPER
      - ZOMBIE

  # Drop spawner when players break it.
  minable:
    enabled: true
    # It needs silktouch to drop spawner.
    needs-silktouch: false

  mine-limiter:
    limiter1: # can define unlimited amount of limiters.
      world: resource
      mob-type: ZOMBIE
      amount: 1
      action: CANCEL # or NO_DROP
    limiter2:
      world: resource
      mob-type: SKELETON
      amount: 1
      action: CANCEL
    limiter3:
      world: resource
      mob-type: SPIDER
      amount: 1
      action: CANCEL
    limiter4:
      world: resource
      mob-type: CAVE_SPIDER
      amount: 1
      action: CANCEL
    limiter5:
      world: resource
      mob-type: SILVERFISH
      amount: 1
      action: CANCEL
    limiter6:
      world: resource_nether
      mob-type: BLAZE
      amount: 1
      action: CANCEL
    limiter7:
      world: resource_nether
      mob-type: MAGMA_CUBE
      amount: 1
      action: CANCEL

  # Limits spanwer amount in specific radius (circle)
  # Only player placement will be affected.
  isolating:
    enabled: true
    radius: 34
    amount: 2
  
  stopped-by-redstone-signal:
    # If reverse is true, spawners stop spawning mob when it not powered.
    reverse: false
    enabled-worlds:
    #- ALL
    - resource


  # Spawn egg cannot change spawner.
  cancel-changing-mob: true

  total-spawnable-mobs:
    DEFAULT: 100000
    ZOMBIE: 100000

# Stack mobs.
mob-stacker:
  enabled: true
  target-spawn-reason:
    - SPAWNER

# Find mob farms.
# If spawn reason includes BLEEDING,
# you can also find normal farm that is not traps.
find-traps:
  enabled: true
  check-spawn-reason:
    - SPAWNER
    - NATURAL
    - SLIME_SPLIT
    - RAID


anti-clickbot:
  enabled: true
  # Available types are: SUMMON_ENEMY, CANCEL, KILL, KICK, CALL_ADMIN
  # SUMMON_ENEMY will teleport nearest agressive mobs
  # CANCEL will cancel clicks
  # KILL will kill clicking player
  # KICK will kick clicking player
  # CALL_ADMIN will notify admins that click bot is used.
  type: SUMMON_ENEMY
  warn-before: true
  warn-message: "You are using auto clicking tools. If you continue to use this, something bad will happen to you!"

prevent-cramming-death-drop: true