name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
author: LazyGon
api-version: 1.17
softdepend:
  - "WorldGuard"

commands:
  ttt:
    description: Main command of this plugin.

permissions:
  ttt.command.getspawner:
    description: Permission for /ttt getspawner subcommand.
    default: op
  ttt.command.resetlimit:
    description: Permission for /ttt resetlimit subcommand.
    default: op
  ttt.command.near:
    description: Permission for /ttt near subcommand.
    default: true
  ttt.bypass.changespawner:
    description: Permission to bypass changing mob spawner with spawn egg.
    default: op
  ttt.bypass.unplaceable:
    description: Permission to bypass placing spawner in spawner unplaceable worlds.
    default: op