name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
author: LazyGon
softdepend:
  - "WorldGuard"

commands:
  ttt:
    description: Main command of this plugin.